language: rust
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install libcgal-dev
  - wget https://github.com/Oslandia/SFCGAL/archive/v1.3.6.tar.gz
  - tar -xzvf v1.3.6.tar.gz
  - pushd SFCGAL-1.3.6 && cmake . && make && sudo make install && popd
