language: rust
dist: xenial
sudo: required
compiler:
  - clang
rust:
  - stable
  - beta
  - nightly
before_install:
  - sudo apt-get update
  - sudo apt-get install --force-yes clang-3.9 libclang-3.9-dev libboost-chrono1.58-dev libboost-program-options1.58-dev libboost-filesystem1.58-dev libboost-timer1.58-dev libboost-test1.58-dev libboost-thread1.58-dev libboost-system1.58-dev libboost-serialization1.58-dev libmpfr-dev libgmp-dev cmake
  - wget https://github.com/CGAL/cgal/releases/download/releases%2FCGAL-5.0.3/CGAL-5.0.3.tar.xz
  - tar xJf CGAL-5.0.3.tar.xz
  - cd CGAL-5.0.3 && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=$HOME/CGAL-5.0.3 .. && make && sudo make install && cd ../..
  - wget https://gitlab.com/Oslandia/SFCGAL/-/archive/v1.3.8/SFCGAL-v1.3.8.tar.gz
  - tar -xzvf SFCGAL-v1.3.8.tar.gz
  - cd SFCGAL-v1.3.8 && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make && sudo make install && cd ..
