[package]
name = "sfcgal-sys"
version = "0.1.0"
authors = ["Matthieu Viry <matthieu.viry@univ-grenoble-alpes.fr>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
bindgen = "0.47.1"
cc = "*"
