on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

name: Build documentation on new release
jobs:
  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo apt-get install -y libboost1.74-all-dev libmpfr-dev libgmp-dev cmake wget unzip clang libstdc++-11-dev
          wget https://github.com/CGAL/cgal/releases/download/v5.6.1/CGAL-5.6.1-library.tar.xz
          wget https://gitlab.com/SFCGAL/SFCGAL/-/archive/v1.5.0/SFCGAL-v1.5.0.zip
          tar -xf CGAL-5.6.1-library.tar.xz
          unzip SFCGAL-v1.5.0.zip
          cd CGAL-5.6.1 && cmake . && sudo make install && cd ..
          cd $(ls -d */ | grep SFC) && cmake -DCMAKE_INSTALL_PREFIX=/usr . && make && sudo make install && cd ..
      - run: |
          cargo doc
          echo "<meta http-equiv=refresh content=0;url=sfcgal_sys/index.html>" > target/doc/index.html
          sudo pip install ghp-import
          ghp-import -n target/doc
          git push -fq https://${GITHUB_TOKEN}@github.com/mthh/sfcgal-sys.git gh-pages